### ISSUE TITLE
使用ssm new --private部署后端，使用ssm update更新后变不带--private

### ISSUE THREAD

**Issue by nfervor** [sub-store-org/Sub-Store-Manager-Cli#9]
使用ssm new --private部署后端，使用nginx 配合/path进行反代，这样是127.0.0.1:30000->3000/tcp   ssm-backend.
使用ssm update更新后变成不带--private参数，0.0.0.0:30000->3000/tcp   ssm-backend. 
这样后端ip:3000和domainname/path,都能访问了。 
不注意这样会泄漏订阅节点，能否ssm update 保持部署的参数。

**Comment by DesnLee** [comment]
已发布修复 https://github.com/sub-store-org/Sub-Store-Manager-Cli/releases/tag/0.0.11
